-- 增加订单的实收金额
ALTER TABLE OrderItems ADD COLUMN RealPrice DECIMAL(10,2) DEFAULT 0.0;
ALTER TABLE OrderItems ADD COLUMN DeliverPrice DECIMAL(10,2) DEFAULT 0.0;

ALTER TABLE TestOrderItems ADD COLUMN RealPrice DECIMAL(10,2) DEFAULT 0.0;
ALTER TABLE TestOrderItems ADD COLUMN DeliverPrice DECIMAL(10,2) DEFAULT 0.0;

